# Generated by Django 3.1.1 on 2020-09-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.timestampedmodel')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('blog.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.timestampedmodel')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('blog.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.timestampedmodel')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='blog/post/photo/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_post_list', to=settings.AUTH_USER_MODEL)),
                ('like_user_set', models.ManyToManyField(blank=True, related_name='like_post_list', to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_post_list', to='blog.category')),
                ('tag_list', models.ManyToManyField(blank=True, related_name='tag_post_list', to='blog.Tag')),
            ],
            bases=('blog.timestampedmodel',),
        ),
    ]
